import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Main/Layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative min-h-screen">
          <div className="absolute inset-0 bg-main"></div>
          <div className="absolute inset-0 bg-white opacity-[0.01]" />
          <div className="relative">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
